import type { Entry } from '../../core/i18n/translations';

/** Texte für /bestellen und /bestellen/danke. */
export const SHOP_CONTENT: Record<string, Entry> = {
  'shop.label': { de: 'Online-Bestellung', fr: 'Commande en ligne', en: 'Order online', tr: 'Online sipariş', ku: 'Siparîşa serhêl' },
  'shop.title': {
    de: 'Bewertungskarten<br /><em>online bestellen</em>.',
    fr: 'Commander vos cartes<br /><em>en ligne</em>.',
    en: 'Order review cards<br /><em>online</em>.',
    tr: 'Değerlendirme kartlarını<br /><em>online sipariş edin</em>.',
    ku: 'Kartên nirxandinê<br /><em>serhêl siparîş bikin</em>.',
  },
  'shop.intro': {
    de: 'Menge wählen, bezahlen, fertig. Wir richten jede Karte auf Ihr Google-Profil ein und melden uns vor dem Druck.',
    fr: 'Choisissez la quantité, payez, c’est fait. Nous configurons chaque carte sur votre profil Google et vous contactons avant l’impression.',
    en: 'Choose the quantity, pay, done. We set every card up for your Google profile and get in touch before printing.',
    tr: 'Adedi seçin, ödeyin, bu kadar. Her kartı Google profilinize göre ayarlar, baskıdan önce sizinle iletişime geçeriz.',
    ku: 'Hejmarê hilbijêrin, bidin, temam. Em her kartê li gorî profîla we ya Google saz dikin û berî çapê bi we re têkilî datînin.',
  },
  'shop.soon.title': { de: 'Online-Bestellung folgt in Kürze.', fr: 'La commande en ligne arrive bientôt.', en: 'Online ordering is coming soon.', tr: 'Online sipariş yakında.', ku: 'Siparîşa serhêl di demek nêzîk de.' },
  'shop.soon.text': {
    de: 'Bis dahin bestellen Sie ganz einfach per Anfrage — wir melden uns innerhalb eines Werktags.',
    fr: 'D’ici là, commandez simplement via une demande — nous répondons sous un jour ouvré.',
    en: 'Until then, simply order via an enquiry — we reply within one working day.',
    tr: 'O zamana kadar talep formuyla kolayca sipariş verebilirsiniz — bir iş günü içinde dönüş yaparız.',
    ku: 'Heta wê demê bi daxwazekê bi hêsanî siparîş bikin — em di nav rojeke kar de bersiv didin.',
  },
  'shop.forms': { de: 'Einzeln', fr: 'À l’unité', en: 'Single items', tr: 'Tek tek', ku: 'Yek bi yek' },
  'shop.packages': { de: 'Pakete', fr: 'Formules', en: 'Bundles', tr: 'Paketler', ku: 'Pakêt' },
  'shop.cards': { de: 'Eigene NFC-Karten', fr: 'Vos propres cartes NFC', en: 'Your own NFC cards', tr: 'Kendi NFC kartlarınız', ku: 'Kartên NFC yên we' },
  'shop.cards.note': {
    de: 'Karte mit eigener Seite auf unserer Domain — kein fremder Anbieter, kein Abo. Nach der Bestellung richten wir den Inhalt mit Ihnen ein: Logo, Kontaktdaten und Links, bei der Geschenkkarte Fotos und ein Lied.',
    fr: 'Une carte avec sa propre page sur notre domaine — aucun prestataire tiers, aucun abonnement. Après la commande, nous en préparons le contenu avec vous : logo, coordonnées et liens ; pour la carte cadeau, photos et musique.',
    en: 'A card with its own page on our domain — no third-party provider, no subscription. After ordering we set the content up with you: logo, contact details and links; for the gift card, photos and a song.',
    tr: 'Kendi alan adımızda kendi sayfası olan kart — üçüncü firma yok, abonelik yok. Siparişten sonra içeriği sizinle kuruyoruz: logo, iletişim bilgileri ve linkler; hediye kartında fotoğraflar ve bir şarkı.',
    ku: 'Kartek bi rûpela xwe li ser navê me — ne pêşkêşkarê biyanî, ne abone. Piştî siparîşê em naverokê bi we re saz dikin: logo, agahiyên pêwendiyê û girêdan; ji bo karta diyariyê wêne û stranek.',
  },
  'shop.card.business': { de: 'Digitale Visitenkarte (NFC)', fr: 'Carte de visite numérique (NFC)', en: 'Digital business card (NFC)', tr: 'Dijital kartvizit (NFC)', ku: 'Karta karsaziyê ya dîjîtal (NFC)' },
  'shop.card.gift': { de: 'Geschenkkarte (NFC)', fr: 'Carte cadeau (NFC)', en: 'Gift card (NFC)', tr: 'Hediye kartı (NFC)', ku: 'Karta diyariyê (NFC)' },
  'shop.minus': { de: 'Weniger', fr: 'Moins', en: 'Fewer', tr: 'Azalt', ku: 'Kêmtir' },
  'shop.plus': { de: 'Mehr', fr: 'Plus', en: 'More', tr: 'Artır', ku: 'Zêdetir' },
  'shop.details': { de: 'Für die Einrichtung', fr: 'Pour la configuration', en: 'For the setup', tr: 'Kurulum için', ku: 'Ji bo sazkirinê' },
  'shop.business': { de: 'Name des Betriebs (steht auf der Karte)', fr: 'Nom de l’établissement (imprimé sur la carte)', en: 'Business name (printed on the card)', tr: 'İşletme adı (kartta yazacak)', ku: 'Navê karsaziyê (li ser kartê)' },
  'shop.google': { de: 'Link zu Ihrem Google-Profil (falls vorhanden)', fr: 'Lien vers votre fiche Google (si elle existe)', en: 'Link to your Google profile (if you have one)', tr: 'Google profil linkiniz (varsa)', ku: 'Girêdana profîla we ya Google (ger hebe)' },
  'shop.total': { de: 'Gesamt', fr: 'Total', en: 'Total', tr: 'Toplam', ku: 'Giştî' },
  'shop.shipping': { de: 'Versand', fr: 'Livraison', en: 'Shipping', tr: 'Kargo', ku: 'Şandin' },
  'shop.shipping.free': { de: 'Versand innerhalb Deutschlands inklusive', fr: 'Livraison en Allemagne incluse', en: 'Shipping within Germany included', tr: 'Almanya içi kargo dahil', ku: 'Şandina li Almanyayê tê de' },
  'shop.vat': {
    de: 'Endpreise. Als Kleinunternehmer nach § 19 UStG wird keine Umsatzsteuer berechnet.',
    fr: 'Prix finaux. Micro-entreprise selon le § 19 UStG : pas de TVA facturée.',
    en: 'Final prices. As a small business under § 19 UStG, no VAT is charged.',
    tr: 'Nihai fiyatlar. § 19 UStG kapsamında küçük işletme olarak KDV alınmaz.',
    ku: 'Bihayên dawî. Wek karsaziya piçûk li gorî § 19 UStG baca nirxê zêde nayê girtin.',
  },
  'shop.cart': { de: 'Warenkorb', fr: 'Panier', en: 'Cart', tr: 'Sepet', ku: 'Selik' },
  'shop.cart.add': { de: 'In den Warenkorb', fr: 'Ajouter au panier', en: 'Add to cart', tr: 'Sepete ekle', ku: 'Têxe selikê' },
  'shop.cart.empty': {
    de: 'Ihr Warenkorb ist noch leer. Wählen Sie links eine Karte oder ein Paket.',
    fr: 'Votre panier est encore vide. Choisissez une carte ou une formule à gauche.',
    en: 'Your cart is still empty. Pick a card or a bundle on the left.',
    tr: 'Sepetiniz henüz boş. Soldan bir kart ya da paket seçin.',
    ku: 'Selika we hîn vala ye. Ji milê çepê kartek an pakêtek hilbijêrin.',
  },
  'shop.cart.clear': { de: 'Leeren', fr: 'Vider', en: 'Clear', tr: 'Boşalt', ku: 'Vala bike' },
  'shop.cart.remove': { de: 'Entfernen', fr: 'Retirer', en: 'Remove', tr: 'Çıkar', ku: 'Rake' },
  'shop.cart.each': { de: 'je Stück', fr: 'l’unité', en: 'each', tr: 'adet', ku: 'her yek' },
  'shop.legal.consent': {
    de: 'Ich habe die AGB und die Widerrufsbelehrung gelesen und akzeptiere sie.',
    fr: 'J’ai lu et j’accepte les CGV et les informations sur le droit de rétractation.',
    en: 'I have read and accept the terms and the withdrawal policy.',
    tr: 'Satış koşullarını ve cayma hakkı bilgilendirmesini okudum ve kabul ediyorum.',
    ku: 'Min mercên firotanê û agahdariya mafê vekişînê xwendin û ez wan dipejirînim.',
  },
  'shop.legal.delivery': {
    de: 'Lieferzeit: 5–10 Werktage nach Ihrer Freigabe. Versand nur innerhalb Deutschlands.',
    fr: 'Délai de livraison : 5 à 10 jours ouvrés après votre validation. Livraison en Allemagne uniquement.',
    en: 'Delivery: 5–10 working days after your approval. Shipping within Germany only.',
    tr: 'Teslim süresi: onayınızdan sonra 5–10 iş günü. Kargo yalnızca Almanya içi.',
    ku: 'Dema radestkirinê: 5–10 rojên kar piştî pejirandina we. Şandin tenê li Almanyayê.',
  },
  'shop.legal.custom': {
    de: 'Die Karten werden für Sie personalisiert. Den Entwurf erhalten Sie vorab per E-Mail — bis zu Ihrer Freigabe können Sie kostenlos stornieren. Mit der Freigabe beginnt die Herstellung; danach besteht nach § 312g Abs. 2 Nr. 1 BGB kein Widerrufsrecht.',
    fr: 'Les cartes sont personnalisées pour vous. Vous recevez la maquette par e-mail au préalable — vous pouvez annuler gratuitement jusqu’à votre validation. La validation lance la fabrication ; ensuite le droit de rétractation ne s’applique plus (§ 312g al. 2 n° 1 BGB).',
    en: 'The cards are personalised for you. You receive the draft by email beforehand — you can cancel free of charge until you approve it. Approval starts production; after that there is no right of withdrawal (§ 312g(2) no. 1 BGB).',
    tr: 'Kartlar size özel hazırlanır. Taslağı önceden e-postayla alırsınız — onaylayana kadar ücretsiz iptal edebilirsiniz. Onayla üretim başlar; sonrasında cayma hakkı bulunmaz (§ 312g Abs. 2 Nr. 1 BGB).',
    ku: 'Kart ji bo we bi taybetî tên amade kirin. Hûn reşnivîsê berê bi e-nameyê distînin — heta ku hûn wê pejirînin hûn dikarin bêpare betal bikin. Bi pejirandinê hilberîn dest pê dike; piştî wê mafê vekişînê nîne (§ 312g Abs. 2 Nr. 1 BGB).',
  },
  'shop.legal.langnote': {
    de: 'Die Rechtstexte liegen auf Deutsch vor.',
    fr: 'Les textes juridiques sont disponibles en allemand.',
    en: 'The legal texts are provided in German.',
    tr: 'Yasal metinler Almanca olarak sunulur.',
    ku: 'Nivîsên hiqûqî bi Almanî ne.',
  },
  'shop.submit': { de: 'Zahlungspflichtig bestellen', fr: 'Commander avec obligation de paiement', en: 'Order and pay', tr: 'Siparişi ver ve öde', ku: 'Siparîş bike û bide' },
  'shop.pay': {
    de: 'Sie werden zur sicheren Bezahlung bei Stripe weitergeleitet.',
    fr: 'Vous serez redirigé vers le paiement sécurisé Stripe.',
    en: 'You will be taken to secure payment with Stripe.',
    tr: 'Güvenli ödeme için Stripe’a yönlendirileceksiniz.',
    ku: 'Hûn ê ji bo dayîna ewle berbi Stripe ve werin şandin.',
  },
  'shop.empty': { de: 'Bitte wählen Sie mindestens ein Produkt.', fr: 'Veuillez choisir au moins un produit.', en: 'Please choose at least one product.', tr: 'Lütfen en az bir ürün seçin.', ku: 'Ji kerema xwe herî kêm berhemekê hilbijêrin.' },
  'shop.error': {
    de: 'Die Bestellung konnte nicht gestartet werden. Bitte versuchen Sie es erneut oder schreiben Sie uns.',
    fr: 'La commande n’a pas pu démarrer. Réessayez ou écrivez-nous.',
    en: 'The order could not be started. Please try again or write to us.',
    tr: 'Sipariş başlatılamadı. Lütfen tekrar deneyin veya bize yazın.',
    ku: 'Siparîş dest pê nekir. Ji kerema xwe dîsa biceribînin an ji me re binivîsin.',
  },
  'shop.thanks.title': { de: 'Danke für Ihre Bestellung!', fr: 'Merci pour votre commande !', en: 'Thank you for your order!', tr: 'Siparişiniz için teşekkürler!', ku: 'Spas ji bo siparîşa we!' },
  'shop.thanks.text': {
    de: 'Die Bestätigung kommt per E-Mail. Wir richten Ihre Karten ein und melden uns vor dem Druck mit dem Entwurf.',
    fr: 'La confirmation arrive par e-mail. Nous configurons vos cartes et vous envoyons la maquette avant impression.',
    en: 'Your confirmation is on its way by email. We set up your cards and send you the draft before printing.',
    tr: 'Onay e-postayla gelecek. Kartlarınızı hazırlar, baskıdan önce taslağı size göndeririz.',
    ku: 'Pejirandin bi e-nameyê tê. Em kartên we amade dikin û berî çapê reşnivîsê ji we re dişînin.',
  },
  'shop.thanks.back': { de: 'Zur Startseite', fr: 'Retour à l’accueil', en: 'Back to home', tr: 'Ana sayfaya dön', ku: 'Vegere rûpela destpêkê' },
  'seo.shop.title': {
    de: 'Bewertungskarten online bestellen | Breisgau Digital',
    fr: 'Commander des cartes d’avis en ligne | Breisgau Digital',
    en: 'Order review cards online | Breisgau Digital',
    tr: 'Değerlendirme kartlarını online sipariş edin | Breisgau Digital',
    ku: 'Kartên nirxandinê serhêl siparîş bikin | Breisgau Digital',
  },
};
