import type { Entry } from '../../core/i18n/translations';

/** Texte für /bestellen und /bestellen/danke. */
export const SHOP_CONTENT: Record<string, Entry> = {
  'shop.label': { de: 'Online-Bestellung', fr: 'Commande en ligne', en: 'Order online', tr: 'Online sipariş', ku: 'Siparîşa serhêl' },
  'shop.title': {
    de: 'Bewertungskarten<br /><em>online bestellen</em>.',
    fr: 'Commander vos cartes<br /><em>en ligne</em>.',
    en: 'Order review cards<br /><em>online</em>.',
    tr: 'Değerlendirme kartlarını<br /><em>online sipariş edin</em>.',
    ku: 'Kartên nirxandinê<br /><em>serhêl siparîş bikin</em>.',
  },
  'shop.intro': {
    de: 'Menge wählen, bezahlen, fertig. Wir richten jede Karte auf Ihr Google-Profil ein und melden uns vor dem Druck.',
    fr: 'Choisissez la quantité, payez, c’est fait. Nous configurons chaque carte sur votre profil Google et vous contactons avant l’impression.',
    en: 'Choose the quantity, pay, done. We set every card up for your Google profile and get in touch before printing.',
    tr: 'Adedi seçin, ödeyin, bu kadar. Her kartı Google profilinize göre ayarlar, baskıdan önce sizinle iletişime geçeriz.',
    ku: 'Hejmarê hilbijêrin, bidin, temam. Em her kartê li gorî profîla we ya Google saz dikin û berî çapê bi we re têkilî datînin.',
  },
  'shop.soon.title': { de: 'Online-Bestellung folgt in Kürze.', fr: 'La commande en ligne arrive bientôt.', en: 'Online ordering is coming soon.', tr: 'Online sipariş yakında.', ku: 'Siparîşa serhêl di demek nêzîk de.' },
  'shop.soon.text': {
    de: 'Bis dahin bestellen Sie ganz einfach per Anfrage — wir melden uns innerhalb eines Werktags.',
    fr: 'D’ici là, commandez simplement via une demande — nous répondons sous un jour ouvré.',
    en: 'Until then, simply order via an enquiry — we reply within one working day.',
    tr: 'O zamana kadar talep formuyla kolayca sipariş verebilirsiniz — bir iş günü içinde dönüş yaparız.',
    ku: 'Heta wê demê bi daxwazekê bi hêsanî siparîş bikin — em di nav rojeke kar de bersiv didin.',
  },
  'shop.forms': { de: 'Einzeln', fr: 'À l’unité', en: 'Single items', tr: 'Tek tek', ku: 'Yek bi yek' },
  'shop.packages': { de: 'Pakete', fr: 'Formules', en: 'Bundles', tr: 'Paketler', ku: 'Pakêt' },
  'shop.minus': { de: 'Weniger', fr: 'Moins', en: 'Fewer', tr: 'Azalt', ku: 'Kêmtir' },
  'shop.plus': { de: 'Mehr', fr: 'Plus', en: 'More', tr: 'Artır', ku: 'Zêdetir' },
  'shop.details': { de: 'Für die Einrichtung', fr: 'Pour la configuration', en: 'For the setup', tr: 'Kurulum için', ku: 'Ji bo sazkirinê' },
  'shop.business': { de: 'Name des Betriebs (steht auf der Karte)', fr: 'Nom de l’établissement (imprimé sur la carte)', en: 'Business name (printed on the card)', tr: 'İşletme adı (kartta yazacak)', ku: 'Navê karsaziyê (li ser kartê)' },
  'shop.google': { de: 'Link zu Ihrem Google-Profil (falls vorhanden)', fr: 'Lien vers votre fiche Google (si elle existe)', en: 'Link to your Google profile (if you have one)', tr: 'Google profil linkiniz (varsa)', ku: 'Girêdana profîla we ya Google (ger hebe)' },
  'shop.total': { de: 'Gesamt', fr: 'Total', en: 'Total', tr: 'Toplam', ku: 'Giştî' },
  'shop.shipping': { de: 'Versand', fr: 'Livraison', en: 'Shipping', tr: 'Kargo', ku: 'Şandin' },
  'shop.shipping.free': { de: 'Versand innerhalb Deutschlands inklusive', fr: 'Livraison en Allemagne incluse', en: 'Shipping within Germany included', tr: 'Almanya içi kargo dahil', ku: 'Şandina li Almanyayê tê de' },
  'shop.vat': {
    de: 'Endpreise. Als Kleinunternehmer nach § 19 UStG wird keine Umsatzsteuer berechnet.',
    fr: 'Prix finaux. Micro-entreprise selon le § 19 UStG : pas de TVA facturée.',
    en: 'Final prices. As a small business under § 19 UStG, no VAT is charged.',
    tr: 'Nihai fiyatlar. § 19 UStG kapsamında küçük işletme olarak KDV alınmaz.',
    ku: 'Bihayên dawî. Wek karsaziya piçûk li gorî § 19 UStG baca nirxê zêde nayê girtin.',
  },
  'shop.submit': { de: 'Zahlungspflichtig bestellen', fr: 'Commander avec obligation de paiement', en: 'Order and pay', tr: 'Siparişi ver ve öde', ku: 'Siparîş bike û bide' },
  'shop.pay': {
    de: 'Sie werden zur sicheren Bezahlung bei Stripe weitergeleitet.',
    fr: 'Vous serez redirigé vers le paiement sécurisé Stripe.',
    en: 'You will be taken to secure payment with Stripe.',
    tr: 'Güvenli ödeme için Stripe’a yönlendirileceksiniz.',
    ku: 'Hûn ê ji bo dayîna ewle berbi Stripe ve werin şandin.',
  },
  'shop.empty': { de: 'Bitte wählen Sie mindestens ein Produkt.', fr: 'Veuillez choisir au moins un produit.', en: 'Please choose at least one product.', tr: 'Lütfen en az bir ürün seçin.', ku: 'Ji kerema xwe herî kêm berhemekê hilbijêrin.' },
  'shop.error': {
    de: 'Die Bestellung konnte nicht gestartet werden. Bitte versuchen Sie es erneut oder schreiben Sie uns.',
    fr: 'La commande n’a pas pu démarrer. Réessayez ou écrivez-nous.',
    en: 'The order could not be started. Please try again or write to us.',
    tr: 'Sipariş başlatılamadı. Lütfen tekrar deneyin veya bize yazın.',
    ku: 'Siparîş dest pê nekir. Ji kerema xwe dîsa biceribînin an ji me re binivîsin.',
  },
  'shop.thanks.title': { de: 'Danke für Ihre Bestellung!', fr: 'Merci pour votre commande !', en: 'Thank you for your order!', tr: 'Siparişiniz için teşekkürler!', ku: 'Spas ji bo siparîşa we!' },
  'shop.thanks.text': {
    de: 'Die Bestätigung kommt per E-Mail. Wir richten Ihre Karten ein und melden uns vor dem Druck mit dem Entwurf.',
    fr: 'La confirmation arrive par e-mail. Nous configurons vos cartes et vous envoyons la maquette avant impression.',
    en: 'Your confirmation is on its way by email. We set up your cards and send you the draft before printing.',
    tr: 'Onay e-postayla gelecek. Kartlarınızı hazırlar, baskıdan önce taslağı size göndeririz.',
    ku: 'Pejirandin bi e-nameyê tê. Em kartên we amade dikin û berî çapê reşnivîsê ji we re dişînin.',
  },
  'shop.thanks.back': { de: 'Zur Startseite', fr: 'Retour à l’accueil', en: 'Back to home', tr: 'Ana sayfaya dön', ku: 'Vegere rûpela destpêkê' },
  'seo.shop.title': {
    de: 'Bewertungskarten online bestellen | Breisgau Digital',
    fr: 'Commander des cartes d’avis en ligne | Breisgau Digital',
    en: 'Order review cards online | Breisgau Digital',
    tr: 'Değerlendirme kartlarını online sipariş edin | Breisgau Digital',
    ku: 'Kartên nirxandinê serhêl siparîş bikin | Breisgau Digital',
  },
};
