import type { Entry } from '../../core/i18n/translations';

/**
 * Texte der Smart-Home-Seite. Werden von SmartHomeComponent beim
 * I18nService registriert und landen so im Lazy-Chunk der Seite.
 */
export const SMART_HOME_CONTENT: Record<string, Entry> = {
  'sh.folio': { de: 'Smart Home', fr: 'Maison connectée', en: 'Smart home', tr: 'Akıllı ev', ku: 'Mala biaqil' },
  'sh.label': { de: 'Produkt', fr: 'Produit', en: 'Product', tr: 'Ürün', ku: 'Berhem' },
  'sh.title': {
    de: 'Smart Home, das<br /><em>Energie und Wege spart</em>.',
    fr: 'Une maison connectée qui<br /><em>économise énergie et trajets</em>.',
    en: 'Smart home tech that<br /><em>saves energy and trips</em>.',
    tr: 'Enerji ve zaman<br /><em>kazandıran akıllı ev</em>.',
    ku: 'Mala biaqil ku<br /><em>enerjî û rê teserûf dike</em>.',
  },
  'sh.title.plain': {
    de: 'Smart Home & Automatisierung für Betriebe und Vermieter',
    fr: 'Maison connectée & automatisation pour entreprises et loueurs',
    en: 'Smart home & automation for businesses and landlords',
    tr: 'İşletmeler ve ev sahipleri için akıllı ev ve otomasyon',
    ku: 'Mala biaqil û otomasyon ji bo karsazî û kirêdaran',
  },
  'sh.intro': {
    de: 'Heizung, Licht und Zutritt, die sich selbst steuern — im Laden, in der Praxis, im Büro oder in der Ferienwohnung. <strong>Funkbasiert, ohne neue Kabel, lokal gesteuert statt über eine fremde Cloud.</strong>',
    fr: 'Chauffage, éclairage et accès qui se pilotent tout seuls — en boutique, au cabinet, au bureau ou en location saisonnière. <strong>Sans fil, sans nouveaux câbles, piloté en local plutôt que via un cloud tiers.</strong>',
    en: 'Heating, lighting and access that run themselves — in your shop, practice, office or holiday flat. <strong>Wireless, no new cables, controlled locally instead of through someone else’s cloud.</strong>',
    tr: 'Kendi kendini yöneten ısıtma, aydınlatma ve giriş — dükkânda, muayenehanede, ofiste veya tatil dairesinde. <strong>Kablosuz, yeni kablo yok, yabancı bir bulut yerine yerel kontrol.</strong>',
    ku: 'Germkirin, ronahî û ketin ku xwe bi xwe birêve diçin — li dikanê, muayenexaneyê, nivîsgehê an xaniyê betlaneyê. <strong>Bêtel, bê kabloyên nû, herêmî tê birêvebirin, ne bi ewrê kesekî din.</strong>',
  },
  'sh.cta.check': { de: 'Smart-Home-Check buchen', fr: 'Réserver le diagnostic', en: 'Book a smart-home check', tr: 'Akıllı ev kontrolü ayarla', ku: 'Kontrola mala biaqil bigire' },
  'sh.cta.order': { de: 'Anfragen', fr: 'Demander', en: 'Enquire', tr: 'Talep et', ku: 'Daxwaz bike' },
  'sh.img.alt': {
    de: 'Smart-Home-Geräte von oben: Smartphone mit Steuerungs-App, Thermostat, Türschloss-Tastatur, Zwischenstecker, Tür- und Bewegungssensor',
    fr: 'Équipements domotiques vus du dessus : smartphone avec appli, thermostat, clavier de serrure, prise connectée, capteurs de porte et de mouvement',
    en: 'Smart-home devices from above: smartphone with control app, thermostat, door-lock keypad, smart plug, door and motion sensors',
    tr: 'Üstten akıllı ev cihazları: kontrol uygulamalı telefon, termostat, kapı kilidi tuş takımı, akıllı priz, kapı ve hareket sensörü',
    ku: 'Amûrên mala biaqil ji jor ve: telefon bi sepana kontrolê, termostat, klavyeya kilîta derî, prîza biaqil, sensorên derî û tevgerê',
  },
  'sh.use.label': { de: 'Anwendungen', fr: 'Usages', en: 'Use cases', tr: 'Kullanım alanları', ku: 'Karanîn' },
  'sh.use.title': {
    de: 'Wo sich Automatisierung<br /><em>wirklich rechnet</em>.',
    fr: 'Là où l’automatisation<br /><em>est vraiment rentable</em>.',
    en: 'Where automation<br /><em>actually pays off</em>.',
    tr: 'Otomasyonun<br /><em>gerçekten kazandırdığı yerler</em>.',
    ku: 'Li ku derê otomasyon<br /><em>bi rastî qezenc dike</em>.',
  },
  'sh.use1.t': { de: 'Heizung nach Öffnungszeiten', fr: 'Chauffage selon les horaires', en: 'Heating by opening hours', tr: 'Açılış saatine göre ısıtma', ku: 'Germkirin li gorî demjimêran' },
  'sh.use1.d': {
    de: 'Smarte Thermostate heizen nur, wenn geöffnet ist, und senken nachts und am Wochenende ab. Fenster auf? Heizung aus.',
    fr: 'Les thermostats connectés ne chauffent que pendant l’ouverture et baissent la nuit et le week-end. Fenêtre ouverte ? Chauffage coupé.',
    en: 'Smart thermostats only heat while you are open and turn down at night and at weekends. Window open? Heating off.',
    tr: 'Akıllı termostatlar yalnızca açıkken ısıtır, gece ve hafta sonu düşürür. Pencere açık mı? Isıtma kapanır.',
    ku: 'Termostatên biaqil tenê dema vekirî germ dikin û bi şev û dawiya hefteyê kêm dikin. Pencere vekirî ye? Germkirin tê girtin.',
  },
  'sh.use2.t': { de: 'Self-Check-in für Gäste', fr: 'Arrivée autonome', en: 'Guest self check-in', tr: 'Misafir için kendi kendine giriş', ku: 'Ketina xweser ji bo mêvanan' },
  'sh.use2.d': {
    de: 'Smartes Türschloss mit eigenem Code pro Gast. Keine Schlüsselübergabe, der Code verfällt nach der Abreise.',
    fr: 'Serrure connectée avec un code par hôte. Pas de remise de clés, le code expire après le départ.',
    en: 'A smart lock with its own code per guest. No key handover, and the code expires after check-out.',
    tr: 'Her misafire ayrı kodlu akıllı kilit. Anahtar teslimi yok, kod ayrılıştan sonra geçersiz olur.',
    ku: 'Kilîteke biaqil bi kodeke taybet ji bo her mêvanî. Radestkirina mifteyan tune, kod piştî derketinê betal dibe.',
  },
  'sh.use3.t': { de: 'Licht & Schaufenster', fr: 'Éclairage & vitrine', en: 'Lighting & shop window', tr: 'Işık ve vitrin', ku: 'Ronahî û vîtrîn' },
  'sh.use3.d': {
    de: 'Licht nach Zeitplan oder Bewegung, das Schaufenster abends automatisch an und nachts aus.',
    fr: 'Éclairage selon un planning ou la présence, vitrine allumée le soir et éteinte la nuit automatiquement.',
    en: 'Lights on a schedule or by motion, the shop window on in the evening and off at night — automatically.',
    tr: 'Zaman planına veya harekete göre ışık; vitrin akşam otomatik açılır, gece kapanır.',
    ku: 'Ronahî li gorî plan an tevgerê, vîtrîn êvarê bixweber vêdikeve û bi şev vedimire.',
  },
  'sh.use4.t': { de: 'Energie im Blick', fr: 'Énergie sous contrôle', en: 'Energy at a glance', tr: 'Enerji kontrolde', ku: 'Enerjî li ber çavan' },
  'sh.use4.d': {
    de: 'Zwischenstecker und Zähler-Auslesung zeigen, welche Geräte Strom fressen — übersichtlich auf dem Handy.',
    fr: 'Prises et lecture du compteur montrent quels appareils consomment — clairement, sur votre téléphone.',
    en: 'Smart plugs and meter readings show which devices eat power — clearly laid out on your phone.',
    tr: 'Akıllı prizler ve sayaç okuma hangi cihazın elektrik yediğini gösterir — telefonunuzda net biçimde.',
    ku: 'Prîzên biaqil û xwendina jimarvanê nîşan didin ka kîjan amûr elektrîkê dixwin — bi zelalî li ser telefonê.',
  },
  'sh.use5.t': { de: 'Sicherheit & Meldungen', fr: 'Sécurité & alertes', en: 'Security & alerts', tr: 'Güvenlik ve bildirimler', ku: 'Ewlehî û agahdarî' },
  'sh.use5.d': {
    de: 'Tür- und Fenstersensoren, Wassermelder im Keller: eine Nachricht aufs Handy statt einer bösen Überraschung am Montag.',
    fr: 'Capteurs de porte et de fenêtre, détecteur de fuite à la cave : une notification plutôt qu’une mauvaise surprise le lundi.',
    en: 'Door and window sensors, a leak detector in the basement: a message on your phone instead of a nasty surprise on Monday.',
    tr: 'Kapı ve pencere sensörleri, bodrumda su kaçağı dedektörü: pazartesi kötü sürpriz yerine telefona bildirim.',
    ku: 'Sensorên derî û pencereyê, detektora avê li jêrzemînê: peyamek li ser telefonê li şûna surprîzeke xirab roja duşemê.',
  },
  'sh.use6.t': { de: 'Eine App für alles', fr: 'Une appli pour tout', en: 'One app for everything', tr: 'Her şey için tek uygulama', ku: 'Sepanek ji bo her tiştî' },
  'sh.use6.d': {
    de: 'Statt fünf Hersteller-Apps eine Oberfläche — auf dem Handy, als Tablet an der Wand oder per Sprachbefehl.',
    fr: 'Une seule interface au lieu de cinq applis — sur téléphone, sur une tablette murale ou à la voix.',
    en: 'One interface instead of five vendor apps — on your phone, a wall-mounted tablet or by voice.',
    tr: 'Beş üretici uygulaması yerine tek arayüz — telefonda, duvardaki tablette veya sesli komutla.',
    ku: 'Li şûna pênc sepanên hilberîneran, navrûyek — li ser telefonê, tabletek li ser dîwêr an bi dengê.',
  },
  'sh.pkg.label': { de: 'Pakete', fr: 'Offres', en: 'Packages', tr: 'Paketler', ku: 'Pakêt' },
  'sh.pkg.title': {
    de: 'Klein anfangen,<br /><em>später erweitern</em>.',
    fr: 'Commencer petit,<br /><em>étendre ensuite</em>.',
    en: 'Start small,<br /><em>grow later</em>.',
    tr: 'Küçük başlayın,<br /><em>sonra büyütün</em>.',
    ku: 'Biçûk dest pê bikin,<br /><em>paşê mezin bikin</em>.',
  },
  'sh.pkg.badge': { de: 'Beliebt', fr: 'Populaire', en: 'Popular', tr: 'Popüler', ku: 'Populer' },
  'sh.pkg.check.name': { de: 'Smart-Home-Check', fr: 'Diagnostic', en: 'Smart-home check', tr: 'Akıllı ev kontrolü', ku: 'Kontrola mala biaqil' },
  'sh.pkg.check.for': {
    de: 'Für alle, die erst wissen wollen, was sich lohnt', fr: 'Pour savoir d’abord ce qui est rentable', en: 'For anyone who wants to know what pays off first', tr: 'Önce neyin değdiğini bilmek isteyenler için', ku: 'Ji bo kesên ku pêşî dixwazin bizanin çi hêja ye',
  },
  'sh.pkg.check.p1': {
    de: 'Termin vor Ort, ca. 60 Minuten', fr: 'Visite sur place, environ 60 minutes', en: 'On-site visit, about 60 minutes', tr: 'Yerinde ziyaret, yaklaşık 60 dakika', ku: 'Serdana li cih, nêzîkî 60 deqe',
  },
  'sh.pkg.check.p2': {
    de: 'Bestandsaufnahme: Heizung, Licht, Türen, WLAN', fr: 'État des lieux : chauffage, éclairage, portes, Wi-Fi', en: 'Survey: heating, lighting, doors, Wi-Fi', tr: 'Mevcut durum: ısıtma, ışık, kapılar, Wi-Fi', ku: 'Nirxandina rewşê: germkirin, ronahî, derî, WLAN',
  },
  'sh.pkg.check.p3': {
    de: 'Schriftliche Empfehlung mit Geräteliste und Festpreis', fr: 'Recommandation écrite avec liste d’appareils et prix fixe', en: 'Written recommendation with device list and fixed price', tr: 'Cihaz listesi ve sabit fiyatlı yazılı öneri', ku: 'Pêşniyara nivîskî bi lîsteya amûran û bihayê sabît',
  },
  'sh.pkg.check.p4': {
    de: 'Wird bei Beauftragung voll angerechnet', fr: 'Entièrement déduit en cas de commande', en: 'Fully credited if you go ahead', tr: 'Sipariş verirseniz tamamen düşülür', ku: 'Heke hûn ferman bikin, bi tevahî tê hesibandin',
  },
  'sh.pkg.start.name': { de: 'Starter', fr: 'Essentiel', en: 'Starter', tr: 'Başlangıç', ku: 'Destpêk' },
  'sh.pkg.start.for': {
    de: 'Für einen Laden, eine Praxis oder eine Ferienwohnung', fr: 'Pour une boutique, un cabinet ou une location', en: 'For one shop, practice or holiday flat', tr: 'Bir dükkân, muayenehane veya tatil dairesi için', ku: 'Ji bo dikanek, muayenexaneyek an xaniyekî betlaneyê',
  },
  'sh.pkg.start.p1': {
    de: 'Lokale Zentrale inklusive Einrichtung', fr: 'Box locale, installation comprise', en: 'Local hub including setup', tr: 'Kurulum dahil yerel merkez', ku: 'Navenda herêmî bi sazkirinê re',
  },
  'sh.pkg.start.p2': {
    de: 'Bis zu 6 Geräte: Thermostate, Sensoren, Zwischenstecker', fr: 'Jusqu’à 6 appareils : thermostats, capteurs, prises', en: 'Up to 6 devices: thermostats, sensors, smart plugs', tr: '6 cihaza kadar: termostat, sensör, akıllı priz', ku: 'Heta 6 amûran: termostat, sensor, prîz',
  },
  'sh.pkg.start.p3': {
    de: 'Zeitpläne passend zu Ihren Öffnungszeiten', fr: 'Plannings adaptés à vos horaires', en: 'Schedules that match your opening hours', tr: 'Açılış saatlerinize uygun programlar', ku: 'Plan li gorî demjimêrên we yên vekirinê',
  },
  'sh.pkg.start.p4': {
    de: 'Einweisung und 30 Tage Nachbetreuung', fr: 'Prise en main et 30 jours de suivi', en: 'Walkthrough and 30 days of follow-up support', tr: 'Kullanım eğitimi ve 30 gün destek', ku: 'Perwerde û 30 roj piştgirî',
  },
  'sh.pkg.betrieb.name': { de: 'Betrieb', fr: 'Entreprise', en: 'Business', tr: 'İşletme', ku: 'Karsazî' },
  'sh.pkg.betrieb.for': {
    de: 'Für mehrere Räume, Mitarbeitende oder Wohnungen', fr: 'Pour plusieurs pièces, salariés ou logements', en: 'For several rooms, staff or flats', tr: 'Birden fazla oda, çalışan veya daire için', ku: 'Ji bo çend odeyan, karmendan an xaniyan',
  },
  'sh.pkg.betrieb.p1': {
    de: 'Alles aus Starter, bis zu 20 Geräte', fr: 'Tout l’Essentiel, jusqu’à 20 appareils', en: 'Everything in Starter, up to 20 devices', tr: 'Başlangıç paketinin tamamı, 20 cihaza kadar', ku: 'Hemû tiştên Destpêkê, heta 20 amûran',
  },
  'sh.pkg.betrieb.p2': {
    de: 'Smartes Türschloss oder Zutritt per Code', fr: 'Serrure connectée ou accès par code', en: 'Smart lock or keypad access', tr: 'Akıllı kilit veya kodla giriş', ku: 'Kilîta biaqil an ketin bi kodê',
  },
  'sh.pkg.betrieb.p3': {
    de: 'Energie-Übersicht und Push-Meldungen', fr: 'Suivi énergétique et notifications', en: 'Energy overview and push alerts', tr: 'Enerji özeti ve anlık bildirimler', ku: 'Kurtenêrîna enerjiyê û agahdariyên push',
  },
  'sh.pkg.betrieb.p4': {
    de: 'Fernwartung nach Absprache', fr: 'Maintenance à distance sur demande', en: 'Remote maintenance by arrangement', tr: 'Anlaşmaya göre uzaktan bakım', ku: 'Lênêrîna ji dûr ve bi lihevkirinê',
  },
  'sh.price.note': {
    de: 'Preise für Beratung, Einrichtung und Konfiguration. Geräte berechnen wir zum Einkaufspreis — oder Sie kaufen sie selbst nach unserer Liste. Kleinunternehmer gemäß § 19 UStG — es wird keine Umsatzsteuer ausgewiesen.',
    fr: 'Prix du conseil, de l’installation et de la configuration. Les appareils sont facturés au prix d’achat — ou vous les achetez vous-même d’après notre liste. Petite entreprise au sens du § 19 UStG — la TVA n’est pas facturée.',
    en: 'Prices cover consulting, setup and configuration. Devices are charged at cost — or you buy them yourself from our list. Small-business scheme under § 19 of the German VAT Act — no VAT is shown.',
    tr: 'Fiyatlar danışmanlık, kurulum ve yapılandırmayı kapsar. Cihazları alış fiyatına faturalandırırız — ya da listemize göre kendiniz alırsınız. § 19 UStG uyarınca küçük işletme — KDV gösterilmez.',
    ku: 'Biha şêwirdarî, sazkirin û mîhengkirinê digirin. Amûr bi bihayê kirînê têne hesabkirin — an hûn wan bi xwe li gorî lîsteya me dikirin. Karsaziya biçûk li gorî § 19 UStG — bac nayê nîşandan.',
  },
  'sh.steps.label': { de: 'So läuft es', fr: 'Comment ça marche', en: 'How it works', tr: 'Nasıl işler', ku: 'Çawa dixebite' },
  'sh.steps.title': {
    de: 'Vom Check bis zur<br /><em>fertigen Automatik</em>.',
    fr: 'Du diagnostic<br /><em>à l’automatisation</em>.',
    en: 'From the check<br /><em>to finished automation</em>.',
    tr: 'Kontrolden<br /><em>hazır otomasyona</em>.',
    ku: 'Ji kontrolê heta<br /><em>otomasyona amade</em>.',
  },
  'sh.step1.t': { de: 'Check vor Ort', fr: 'Diagnostic sur place', en: 'On-site check', tr: 'Yerinde kontrol', ku: 'Kontrola li cih' },
  'sh.step1.d': {
    de: 'Wir schauen uns Räume, Heizung, Türen und WLAN an und hören zu, was Sie nervt.',
    fr: 'Nous regardons pièces, chauffage, portes et Wi-Fi, et écoutons ce qui vous agace.',
    en: 'We look at rooms, heating, doors and Wi-Fi — and listen to what annoys you.',
    tr: 'Odalara, ısıtmaya, kapılara ve Wi-Fi’a bakar, sizi neyin rahatsız ettiğini dinleriz.',
    ku: 'Em li ode, germkirin, derî û WLAN dinêrin û guhdarî dikin ka çi we aciz dike.',
  },
  'sh.step2.t': { de: 'Plan & Festpreis', fr: 'Plan & prix fixe', en: 'Plan & fixed price', tr: 'Plan ve sabit fiyat', ku: 'Plan û bihayê sabît' },
  'sh.step2.d': {
    de: 'Sie bekommen eine Geräteliste und einen Festpreis. Nichts wird gekauft, bevor Sie zustimmen.',
    fr: 'Vous recevez une liste d’appareils et un prix fixe. Rien n’est acheté sans votre accord.',
    en: 'You get a device list and a fixed price. Nothing is bought before you agree.',
    tr: 'Cihaz listesi ve sabit fiyat alırsınız. Onayınız olmadan hiçbir şey satın alınmaz.',
    ku: 'Hûn lîsteya amûran û bihayekî sabît distînin. Berî razîbûna we tiştek nayê kirîn.',
  },
  'sh.step3.t': { de: 'Einrichtung', fr: 'Installation', en: 'Setup', tr: 'Kurulum', ku: 'Sazkirin' },
  'sh.step3.d': {
    de: 'Meist an einem Tag — der laufende Betrieb bleibt dabei ungestört.',
    fr: 'Généralement en une journée — sans perturber votre activité.',
    en: 'Usually in a single day — without disrupting your business.',
    tr: 'Çoğunlukla tek günde — işleriniz aksamadan.',
    ku: 'Bi gelemperî di rojekê de — bêyî ku karê we asteng bibe.',
  },
  'sh.step4.t': { de: 'Einweisung', fr: 'Prise en main', en: 'Walkthrough', tr: 'Kullanım eğitimi', ku: 'Perwerde' },
  'sh.step4.d': {
    de: 'Wir zeigen Ihnen und Ihrem Team die App und bleiben danach erreichbar.',
    fr: 'Nous montrons l’appli à vous et à votre équipe, puis restons joignables.',
    en: 'We show you and your team the app — and stay reachable afterwards.',
    tr: 'Uygulamayı size ve ekibinize gösterir, sonrasında ulaşılabilir kalırız.',
    ku: 'Em sepanê nîşanî we û tîma we didin û paşê jî berdest dimînin.',
  },
  'sh.fair.label': { de: 'Datenschutz & Sicherheit', fr: 'Données & sécurité', en: 'Privacy & safety', tr: 'Gizlilik ve güvenlik', ku: 'Nepenî û ewlehî' },
  'sh.fair.title': {
    de: 'Ihre Daten bleiben im Haus.', fr: 'Vos données restent chez vous.', en: 'Your data stays on the premises.', tr: 'Verileriniz evde kalır.', ku: 'Daneyên we li malê dimînin.',
  },
  'sh.fair.text': {
    de: 'Wir setzen auf offene Standards wie Matter und Zigbee. Die Steuerung läuft lokal auf einem kleinen Gerät bei Ihnen — nicht über die Server eines Herstellers. Kameras in Geschäftsräumen richten wir nur DSGVO-konform ein, mit Hinweisschild und ohne Mitarbeiterüberwachung. Arbeiten an der festen 230-Volt-Installation übernimmt ein Elektrofachbetrieb aus der Region.',
    fr: 'Nous misons sur des standards ouverts comme Matter et Zigbee. Le pilotage tourne en local sur un petit boîtier chez vous — pas sur les serveurs d’un fabricant. Les caméras dans des locaux professionnels ne sont installées que conformément au RGPD, avec panneau d’information et sans surveillance des salariés. Les travaux sur l’installation électrique fixe sont confiés à un électricien de la région.',
    en: 'We rely on open standards such as Matter and Zigbee. Control runs locally on a small device at your premises — not on a manufacturer’s servers. Cameras in business premises are only installed GDPR-compliant, with signage and no staff monitoring. Any work on fixed 230-volt wiring is done by a licensed local electrician.',
    tr: 'Matter ve Zigbee gibi açık standartlar kullanırız. Kontrol, bir üreticinin sunucularında değil, sizdeki küçük bir cihazda yerel olarak çalışır. İş yerlerindeki kameraları yalnızca GDPR’a uygun, uyarı levhasıyla ve çalışan takibi olmadan kurarız. Sabit 230 volt tesisattaki işleri bölgeden yetkili bir elektrik firması üstlenir.',
    ku: 'Em standardên vekirî yên wek Matter û Zigbee bi kar tînin. Kontrol li ser amûreke biçûk li cem we herêmî dixebite — ne li ser serverên hilberînerekî. Kameraya li cihên karsaziyê em tenê li gorî DSGVO saz dikin, bi tabelaya agahdariyê û bê çavdêriya karmendan. Karên li ser sazkirina elektrîkê ya 230 voltî ji hêla elektrîkvanekî destûrdar ê herêmê ve têne kirin.',
  },
  'sh.faq.label': { de: 'Fragen', fr: 'Questions', en: 'Questions', tr: 'Sorular', ku: 'Pirs' },
  'sh.faq.title': {
    de: 'Was Kunden<br /><em>vorher wissen wollen</em>.',
    fr: 'Ce que les clients<br /><em>veulent savoir avant</em>.',
    en: 'What customers<br /><em>want to know first</em>.',
    tr: 'Müşterilerin<br /><em>önceden bilmek istedikleri</em>.',
    ku: 'Xerîdar<br /><em>berê dixwazin çi bizanin</em>.',
  },
  'sh.faq1.q': { de: 'Muss ich dafür Kabel verlegen lassen?', fr: 'Faut-il tirer des câbles ?', en: 'Do I need new cables?', tr: 'Kablo çektirmem gerekir mi?', ku: 'Ma divê ez kabloyan bikişînim?' },
  'sh.faq1.a': {
    de: 'In der Regel nicht. Wir arbeiten mit Funkgeräten, die mit Batterie oder über die Steckdose laufen. Wo doch einmal an die feste Elektrik muss, holen wir einen Elektrofachbetrieb dazu.',
    fr: 'En général non. Nous utilisons des appareils sans fil, sur pile ou sur prise. S’il faut toucher à l’installation fixe, nous faisons appel à un électricien.',
    en: 'Usually not. We use wireless devices that run on batteries or plug into a socket. Where fixed wiring is involved, we bring in a licensed electrician.',
    tr: 'Genellikle hayır. Pille veya prizden çalışan kablosuz cihazlar kullanırız. Sabit elektrik tesisatına dokunmak gerekirse yetkili bir elektrikçiyle çalışırız.',
    ku: 'Bi gelemperî na. Em amûrên bêtel bi kar tînin ku bi pîlê an bi prîzê dixebitin. Li cihê ku divê dest bidin elektrîka sabît, em elektrîkvanekî destûrdar tînin.',
  },
  'sh.faq2.q': { de: 'Funktioniert das auch ohne Internet?', fr: 'Est-ce que ça marche sans internet ?', en: 'Does it work without internet?', tr: 'İnternet olmadan da çalışır mı?', ku: 'Ma bê înternetê jî dixebite?' },
  'sh.faq2.a': {
    de: 'Ja. Zeitpläne und Automationen laufen lokal weiter. Nur der Fernzugriff per Handy braucht Internet.',
    fr: 'Oui. Plannings et automatisations continuent en local. Seul l’accès à distance par téléphone nécessite internet.',
    en: 'Yes. Schedules and automations keep running locally. Only remote access from your phone needs internet.',
    tr: 'Evet. Programlar ve otomasyonlar yerel olarak çalışmaya devam eder. Yalnızca telefondan uzaktan erişim internet ister.',
    ku: 'Erê. Plan û otomasyon herêmî didomînin. Tenê gihîştina ji dûr ve bi telefonê înternetê dixwaze.',
  },
  'sh.faq3.q': { de: 'Welche Geräte verwenden Sie?', fr: 'Quels appareils utilisez-vous ?', en: 'Which devices do you use?', tr: 'Hangi cihazları kullanıyorsunuz?', ku: 'Hûn kîjan amûran bi kar tînin?' },
  'sh.faq3.a': {
    de: 'Wir sind an keinen Hersteller gebunden und wählen Geräte mit offenen Standards wie Matter oder Zigbee. Vorhandene Geräte und Sprachassistenten binden wir, wo möglich, mit ein.',
    fr: 'Nous ne dépendons d’aucun fabricant et choisissons des appareils aux standards ouverts comme Matter ou Zigbee. Vos appareils et assistants vocaux existants sont intégrés si possible.',
    en: 'We are not tied to any manufacturer and choose devices built on open standards such as Matter or Zigbee. Existing devices and voice assistants are integrated where possible.',
    tr: 'Hiçbir üreticiye bağlı değiliz; Matter veya Zigbee gibi açık standartlı cihazlar seçeriz. Mevcut cihazlarınızı ve sesli asistanlarınızı mümkünse entegre ederiz.',
    ku: 'Em bi tu hilberînerî ve girêdayî nînin û amûrên bi standardên vekirî yên wek Matter an Zigbee hildibijêrin. Amûr û alîkarên dengî yên heyî, heke gengaz be, em tevlî dikin.',
  },
  'sh.faq4.q': { de: 'Lohnt sich das für mich?', fr: 'Est-ce rentable pour moi ?', en: 'Is it worth it for me?', tr: 'Bu benim için değer mi?', ku: 'Ma ev ji bo min hêja ye?' },
  'sh.faq4.a': {
    de: 'Das hängt von Gebäude, Heizung und Öffnungszeiten ab. Genau dafür gibt es den Smart-Home-Check: Danach wissen Sie schwarz auf weiß, was es kostet und wo Sie sparen.',
    fr: 'Cela dépend du bâtiment, du chauffage et des horaires. C’est le rôle du diagnostic : ensuite, vous savez noir sur blanc ce que cela coûte et où vous économisez.',
    en: 'It depends on the building, the heating and your opening hours. That’s what the smart-home check is for: afterwards you know in black and white what it costs and where you save.',
    tr: 'Bina, ısıtma ve açılış saatlerine bağlıdır. Akıllı ev kontrolü tam bunun için var: sonrasında maliyeti ve nerede tasarruf edeceğinizi yazılı olarak bilirsiniz.',
    ku: 'Ev bi avahî, germkirin û demjimêrên vekirinê ve girêdayî ye. Kontrola mala biaqil ji bo vê ye: paşê hûn bi nivîskî dizanin ku çiqas e û li ku derê teserûf dikin.',
  },
  'sh.faq5.q': { de: 'Machen Sie das auch privat?', fr: 'Intervenez-vous aussi chez les particuliers ?', en: 'Do you also work for private homes?', tr: 'Özel evlere de yapıyor musunuz?', ku: 'Hûn ji bo malên taybet jî dikin?' },
  'sh.faq5.a': {
    de: 'Ja. Die Pakete funktionieren im Einfamilienhaus oder in der Mietwohnung genauso — gerade Heizung und Türschloss sind privat sehr beliebt.',
    fr: 'Oui. Les offres fonctionnent aussi bien en maison individuelle qu’en appartement — chauffage et serrure sont très demandés.',
    en: 'Yes. The packages work just as well in a house or a rented flat — heating and smart locks are especially popular at home.',
    tr: 'Evet. Paketler müstakil evde veya kiralık dairede de aynı şekilde çalışır — özellikle ısıtma ve akıllı kilit çok tercih edilir.',
    ku: 'Erê. Pakêt li xaniyê malbatekê an xaniyê kirê jî wisa dixebitin — bi taybetî germkirin û kilîta derî pir têne xwestin.',
  },
  'sh.cta.title': {
    de: 'Wo läuft die Heizung<br /><em>gerade umsonst</em>?',
    fr: 'Où le chauffage tourne-t-il<br /><em>pour rien</em> ?',
    en: 'Where is the heating<br /><em>running for nothing</em>?',
    tr: 'Isıtma şu an<br /><em>boşuna nerede çalışıyor</em>?',
    ku: 'Germkirin niha li ku<br /><em>bê feyde dixebite</em>?',
  },
  'sh.cta.text': {
    de: 'Buchen Sie den Smart-Home-Check. Nach einer Stunde vor Ort wissen Sie, was sich rechnet — und der Betrag wird bei Beauftragung angerechnet.',
    fr: 'Réservez le diagnostic. Après une heure sur place, vous savez ce qui est rentable — et le montant est déduit si vous commandez.',
    en: 'Book the smart-home check. After an hour on site you know what pays off — and the fee is credited if you go ahead.',
    tr: 'Akıllı ev kontrolünü ayarlayın. Yerinde bir saat sonra neyin kazandırdığını bilirsiniz — sipariş verirseniz ücret düşülür.',
    ku: 'Kontrola mala biaqil bigirin. Piştî saetekê li cih hûn dizanin çi qezenc dike — û heke hûn ferman bikin, pere tê hesibandin.',
  },
  'sh.mail.subject': {
    de: 'Anfrage Smart Home', fr: 'Demande maison connectée', en: 'Smart home enquiry', tr: 'Akıllı ev talebi', ku: 'Daxwaza mala biaqil',
  },
  'sh.mail.package': { de: 'Paket', fr: 'Offre', en: 'Package', tr: 'Paket', ku: 'Pakêt' },
  'sh.mail.body': {
    de: 'Guten Tag,\n\nwir interessieren uns für Smart Home.\n\nBetrieb / Objekt: \nOrt: \nWas soll automatisiert werden: \nTelefon für Rückruf: \n\nViele Grüße',
    fr: 'Bonjour,\n\nnous nous intéressons à la maison connectée.\n\nEntreprise / bien : \nLieu : \nCe qu’il faut automatiser : \nTéléphone pour être rappelé : \n\nCordialement',
    en: 'Hello,\n\nwe are interested in smart home tech.\n\nBusiness / property: \nLocation: \nWhat should be automated: \nPhone number for a call back: \n\nBest regards',
    tr: 'Merhaba,\n\nakıllı ev ile ilgileniyoruz.\n\nİşletme / mülk: \nYer: \nNe otomatikleştirilmeli: \nGeri arama için telefon: \n\nİyi çalışmalar',
    ku: 'Rojbaş,\n\nem bi mala biaqil re eleqedar in.\n\nKarsazî / xanî: \nCih: \nÇi divê bixweber bibe: \nTelefon ji bo vegerandinê: \n\nBi silav',
  },
  'seo.sh.title': {
    de: 'Smart Home Freiburg — Heizung, Licht & Türschloss für Betriebe | Breisgau Digital',
    fr: 'Maison connectée à Fribourg — chauffage, éclairage & serrure | Breisgau Digital',
    en: 'Smart home in Freiburg — heating, lighting & smart locks | Breisgau Digital',
    tr: 'Freiburg’da akıllı ev — ısıtma, ışık ve akıllı kilit | Breisgau Digital',
    ku: 'Mala biaqil li Freiburg — germkirin, ronahî û kilîta biaqil | Breisgau Digital',
  },
  'seo.sh.desc': {
    de: 'Smart Home für Läden, Praxen, Büros und Ferienwohnungen in Freiburg und Südbaden: smarte Heizung, Self-Check-in, Licht und Energie-Übersicht. Funkbasiert, lokal gesteuert, zum Festpreis.',
    fr: 'Maison connectée pour boutiques, cabinets, bureaux et locations à Fribourg : chauffage intelligent, arrivée autonome, éclairage et suivi énergétique. Sans fil, en local, à prix fixe.',
    en: 'Smart home for shops, practices, offices and holiday flats in Freiburg and southern Baden: smart heating, self check-in, lighting and energy overview. Wireless, locally controlled, fixed price.',
    tr: 'Freiburg ve Güney Baden’de dükkân, muayenehane, ofis ve tatil daireleri için akıllı ev: akıllı ısıtma, kendi kendine giriş, aydınlatma ve enerji takibi. Kablosuz, yerel kontrol, sabit fiyat.',
    ku: 'Mala biaqil ji bo dikan, muayenexane, nivîsgeh û xaniyên betlaneyê li Freiburg: germkirina biaqil, ketina xweser, ronahî û şopandina enerjiyê. Bêtel, herêmî, bi bihayê sabît.',
  },
};
