import type { Entry } from '../../core/i18n/translations';

/**
 * Texte der Startseite (Hero, Warum wir, Branchen, Ablauf, Referenzen,
 * Region, Ansprechpartner, FAQ). Werden von HomeComponent beim I18nService
 * registriert und landen so im Lazy-Chunk der Seite statt im Hauptbundle.
 */
export const HOME_CONTENT: Record<string, Entry> = {
  'home.hero.title': {
    de: 'Mehr Bewertungen.<br />Mehr Anfragen.<br /><em>Weniger Aufwand.</em>',
    fr: 'Plus d’avis.<br />Plus de demandes.<br /><em>Moins d’effort.</em>',
    en: 'More reviews.<br />More enquiries.<br /><em>Less effort.</em>',
    tr: 'Daha çok yorum.<br />Daha çok talep.<br /><em>Daha az zahmet.</em>',
    ku: 'Bêtir nirxandin.<br />Bêtir daxwaz.<br /><em>Kêmtir zehmet.</em>',
  },
  'home.trust1': { de: 'Festpreis vor Projektstart', fr: 'Prix fixe avant le démarrage', en: 'Fixed price before we start', tr: 'Başlamadan önce sabit fiyat', ku: 'Bihayê sabît berî destpêkê' },
  'home.trust2': { de: 'Persönlich vor Ort', fr: 'En personne, sur place', en: 'In person, on site', tr: 'Yerinde, yüz yüze', ku: 'Li cih, rû bi rû' },
  'home.trust3': { de: 'Erstgespräch kostenlos', fr: 'Premier échange gratuit', en: 'Free first consultation', tr: 'İlk görüşme ücretsiz', ku: 'Hevdîtina yekem belaş e' },
  'home.trust4': { de: 'Einrichtung inklusive', fr: 'Installation incluse', en: 'Setup included', tr: 'Kurulum dahil', ku: 'Sazkirin tê de ye' },
  'home.hero.badge': {
    de: 'Handy dranhalten — fertig', fr: 'Approcher le téléphone — c’est fait', en: 'Tap your phone — done', tr: 'Telefonu yaklaştır — bitti', ku: 'Telefonê nêzîk bike — qediya',
  },
  'home.prod.title': {
    de: 'Drei Produkte.<br /><em>Ein Ansprechpartner.</em>',
    fr: 'Trois produits.<br /><em>Un seul interlocuteur.</em>',
    en: 'Three products.<br /><em>One point of contact.</em>',
    tr: 'Üç ürün.<br /><em>Tek muhatap.</em>',
    ku: 'Sê berhem.<br /><em>Kesek ji bo têkiliyê.</em>',
  },
  'home.prod.subtitle': {
    de: 'Einzeln bestellbar oder kombiniert — wir richten alles ein, erklären es Ihrem Team und bleiben erreichbar.',
    fr: 'À commander séparément ou ensemble — nous installons tout, l’expliquons à votre équipe et restons joignables.',
    en: 'Order one or combine them — we set everything up, explain it to your team and stay reachable.',
    tr: 'Tek tek ya da birlikte sipariş edin — her şeyi kurar, ekibinize anlatır ve ulaşılabilir kalırız.',
    ku: 'Yek bi yek an bi hev re ferman bikin — em her tiştî saz dikin, ji tîma we re rave dikin û berdest dimînin.',
  },
  'home.prod.more.label': { de: 'Außerdem', fr: 'Et aussi', en: 'Also', tr: 'Ayrıca', ku: 'Herwiha' },
  'home.more1': { de: 'Online-Shops', fr: 'Boutiques en ligne', en: 'Online shops', tr: 'Online mağazalar', ku: 'Firotgehên serhêl' },
  'home.more2': { de: 'Online-Terminbuchung', fr: 'Réservation en ligne', en: 'Online booking', tr: 'Online randevu', ku: 'Randevûya serhêl' },
  'home.more3': { de: 'Google-Unternehmensprofil', fr: 'Fiche d’établissement Google', en: 'Google Business Profile', tr: 'Google İşletme Profili', ku: 'Profîla karsaziyê ya Google' },
  'home.more4': { de: 'Digitale Abläufe & Software', fr: 'Processus numériques & logiciels', en: 'Digital workflows & software', tr: 'Dijital süreçler ve yazılım', ku: 'Pêvajoyên dîjîtal û nermalav' },
  'home.why.label': { de: 'Warum wir', fr: 'Pourquoi nous', en: 'Why us', tr: 'Neden biz', ku: 'Çima em' },
  'home.why.title': {
    de: 'Digitalisierung ohne<br /><em>Fachchinesisch</em>.',
    fr: 'La numérisation<br /><em>sans jargon</em>.',
    en: 'Digitalisation<br /><em>without the jargon</em>.',
    tr: 'Teknik jargon olmadan<br /><em>dijitalleşme</em>.',
    ku: 'Dîjîtalkirin<br /><em>bê zimanê teknîkî</em>.',
  },
  'home.why1.t': { de: 'Festpreis, schriftlich', fr: 'Prix fixe, par écrit', en: 'Fixed price, in writing', tr: 'Yazılı sabit fiyat', ku: 'Bihayê sabît, bi nivîskî' },
  'home.why1.d': {
    de: 'Sie wissen vor dem Start, was es kostet. Keine Stundenzettel, keine Überraschungen auf der Rechnung.',
    fr: 'Vous connaissez le coût avant de commencer. Pas de décompte d’heures, pas de surprise sur la facture.',
    en: 'You know the cost before we start. No timesheets, no surprises on the invoice.',
    tr: 'Başlamadan önce maliyeti bilirsiniz. Saat hesabı yok, faturada sürpriz yok.',
    ku: 'Hûn berî destpêkê dizanin ku çiqas e. Ne hesabê saetan, ne jî surprîz li ser fatûreyê.',
  },
  'home.why2.t': { de: 'Vor Ort in Südbaden', fr: 'Sur place dans le sud du Bade', en: 'On site in southern Baden', tr: 'Güney Baden’de yerinde', ku: 'Li başûrê Badenê li cih' },
  'home.why2.d': {
    de: 'Wir kommen in Ihren Betrieb, schauen uns die Abläufe an und richten alles direkt dort ein — kein Callcenter, kein Ticketsystem.',
    fr: 'Nous venons dans votre entreprise, observons votre fonctionnement et installons tout sur place — ni centre d’appels, ni tickets.',
    en: 'We come to your business, look at how you work and set everything up right there — no call centre, no ticket system.',
    tr: 'İşletmenize gelir, işleyişi yerinde görür ve her şeyi orada kurarız — çağrı merkezi yok, destek bileti yok.',
    ku: 'Em tên karsaziya we, li pêvajoyan dinêrin û her tiştî li wir saz dikin — ne navenda telefonê, ne jî sîstema bilêtan.',
  },
  'home.why3.t': { de: 'Alles aus einer Hand', fr: 'Un seul interlocuteur', en: 'Everything from one source', tr: 'Her şey tek elden', ku: 'Her tişt ji destekî' },
  'home.why3.d': {
    de: 'Website, Google-Profil, Bewertungen und Technik im Laden greifen ineinander. Ein Ansprechpartner kennt das ganze Bild.',
    fr: 'Site, fiche Google, avis et équipements en boutique vont ensemble. Un seul interlocuteur a la vue d’ensemble.',
    en: 'Website, Google profile, reviews and in-store tech work together. One contact knows the whole picture.',
    tr: 'Web sitesi, Google profili, yorumlar ve dükkândaki teknoloji birbirine bağlı. Tek muhatap resmin tamamını bilir.',
    ku: 'Malper, profîla Google, nirxandin û teknolojiya dikanê bi hev re dixebitin. Kesek tevahiya wêneyê dizane.',
  },
  'home.why4.t': { de: 'Ihre Daten gehören Ihnen', fr: 'Vos données vous appartiennent', en: 'Your data stays yours', tr: 'Verileriniz size aittir', ku: 'Daneyên we yên we ne' },
  'home.why4.d': {
    de: 'Domain, Inhalte und Zugänge laufen auf Ihren Namen. DSGVO-konform eingerichtet, ohne Knebelvertrag.',
    fr: 'Domaine, contenus et accès sont à votre nom. Conforme au RGPD, sans contrat captif.',
    en: 'Domain, content and logins are in your name. Set up GDPR-compliant, with no lock-in contract.',
    tr: 'Alan adı, içerik ve erişimler sizin adınıza. GDPR uyumlu kurulum, bağlayıcı sözleşme yok.',
    ku: 'Domain, naverok û gihîştin bi navê we ne. Li gorî DSGVO hatiye sazkirin, bê peymana girêdayî.',
  },
  'home.ind.label': { de: 'Für wen', fr: 'Pour qui', en: 'Who it’s for', tr: 'Kimler için', ku: 'Ji bo kê' },
  'home.ind.title': {
    de: 'Gemacht für Betriebe<br /><em>mit Kundschaft vor Ort</em>.',
    fr: 'Pensé pour les entreprises<br /><em>qui reçoivent des clients</em>.',
    en: 'Made for businesses<br /><em>with customers at the door</em>.',
    tr: 'Kapısına müşteri gelen<br /><em>işletmeler için</em>.',
    ku: 'Ji bo karsaziyên ku<br /><em>xerîdar tên ba wan</em>.',
  },
  'home.ind1.t': { de: 'Gastronomie & Cafés', fr: 'Restaurants & cafés', en: 'Restaurants & cafés', tr: 'Restoran ve kafeler', ku: 'Xwaringeh û kafe' },
  'home.ind1.d': {
    de: 'Bewertungskarte am Tisch, Speisekarte online, Heizung nach Öffnungszeiten.',
    fr: 'Carte d’avis sur la table, menu en ligne, chauffage selon les horaires.',
    en: 'Review card on the table, menu online, heating by opening hours.',
    tr: 'Masada değerlendirme kartı, online menü, açılış saatine göre ısıtma.',
    ku: 'Karta nirxandinê li ser maseyê, menûya serhêl, germkirin li gorî demjimêran.',
  },
  'home.ind2.t': { de: 'Handwerk', fr: 'Artisanat', en: 'Trades & crafts', tr: 'Zanaat ve ustalar', ku: 'Pîşesazî û hunerên destan' },
  'home.ind2.d': {
    de: 'Website mit Referenzfotos, Anfrageformular und Bewertungen nach jedem Auftrag.',
    fr: 'Site avec photos de chantiers, formulaire de demande et avis après chaque mission.',
    en: 'Website with project photos, an enquiry form and reviews after every job.',
    tr: 'Referans fotoğraflı site, talep formu ve her işten sonra yorum.',
    ku: 'Malper bi wêneyên karan, forma daxwazê û nirxandin piştî her karî.',
  },
  'home.ind3.t': { de: 'Einzelhandel', fr: 'Commerce de détail', en: 'Retail', tr: 'Perakende', ku: 'Firotina hûr' },
  'home.ind3.d': {
    de: 'Google-Profil mit Öffnungszeiten, Karte an der Kasse, Schaufensterlicht nach Plan.',
    fr: 'Fiche Google avec horaires, carte à la caisse, vitrine éclairée selon un planning.',
    en: 'Google profile with opening hours, card at the till, shop-window lighting on schedule.',
    tr: 'Açılış saatli Google profili, kasada kart, programlı vitrin ışığı.',
    ku: 'Profîla Google bi demjimêran, kart li ber kaseyê, ronahiya vîtrînê li gorî plan.',
  },
  'home.ind4.t': { de: 'Friseur & Kosmetik', fr: 'Coiffure & esthétique', en: 'Hair & beauty', tr: 'Kuaför ve güzellik', ku: 'Porçêker û bedewî' },
  'home.ind4.d': {
    de: 'Online-Terminbuchung, Bewertungskarte am Spiegel, gepflegtes Google-Profil.',
    fr: 'Réservation en ligne, carte d’avis au miroir, fiche Google soignée.',
    en: 'Online booking, a review card at the mirror, a well-kept Google profile.',
    tr: 'Online randevu, aynada değerlendirme kartı, bakımlı Google profili.',
    ku: 'Randevûya serhêl, karta nirxandinê li ber neynikê, profîla Google ya xweşkirî.',
  },
  'home.ind5.t': { de: 'Praxen & Kanzleien', fr: 'Cabinets & études', en: 'Practices & offices', tr: 'Muayenehane ve bürolar', ku: 'Muayenexane û nivîsgeh' },
  'home.ind5.d': {
    de: 'Seriöse Website, Terminanfrage online, Heizung und Licht, die mitdenken.',
    fr: 'Site sérieux, demande de rendez-vous en ligne, chauffage et éclairage intelligents.',
    en: 'A trustworthy website, online appointment requests, heating and lights that think ahead.',
    tr: 'Güven veren site, online randevu talebi, akıllı ısıtma ve aydınlatma.',
    ku: 'Malpereke bi bawerî, daxwaza randevûyê serhêl, germkirin û ronahiya biaqil.',
  },
  'home.ind6.t': { de: 'Ferienwohnungen & Hotels', fr: 'Locations & hôtels', en: 'Holiday flats & hotels', tr: 'Tatil daireleri ve oteller', ku: 'Xaniyên betlaneyê û otêl' },
  'home.ind6.d': {
    de: 'Self-Check-in per Türcode, Heizung aus der Ferne, Buchungsseite in mehreren Sprachen.',
    fr: 'Arrivée autonome par code, chauffage à distance, site de réservation multilingue.',
    en: 'Self check-in with door codes, remote heating, a multilingual booking site.',
    tr: 'Kapı koduyla kendi kendine giriş, uzaktan ısıtma, çok dilli rezervasyon sitesi.',
    ku: 'Ketina xweser bi koda derî, germkirin ji dûr ve, malpera rezervasyonê bi çend zimanan.',
  },
  'home.proc.label': { de: 'Ablauf', fr: 'Déroulement', en: 'How it works', tr: 'Süreç', ku: 'Pêvajo' },
  'home.proc.title': {
    de: 'In vier Schritten<br /><em>digital</em>.',
    fr: 'Numérique<br /><em>en quatre étapes</em>.',
    en: 'Digital<br /><em>in four steps</em>.',
    tr: 'Dört adımda<br /><em>dijital</em>.',
    ku: 'Di çar gavan de<br /><em>dîjîtal</em>.',
  },
  'home.proc1.t': { de: 'Erstgespräch', fr: 'Premier échange', en: 'First conversation', tr: 'İlk görüşme', ku: 'Axaftina yekem' },
  'home.proc1.d': {
    de: 'Kostenlos, rund 30 Minuten, am Telefon oder bei Ihnen. Sie erzählen, wo es hakt.',
    fr: 'Gratuit, environ 30 minutes, par téléphone ou chez vous. Vous nous dites ce qui coince.',
    en: 'Free, about 30 minutes, by phone or at your place. You tell us where it hurts.',
    tr: 'Ücretsiz, yaklaşık 30 dakika, telefonda ya da sizde. Nerede takıldığınızı anlatırsınız.',
    ku: 'Belaş, nêzîkî 30 deqe, bi telefonê an li cem we. Hûn dibêjin ku li ku derê asteng heye.',
  },
  'home.proc2.t': { de: 'Festpreis-Angebot', fr: 'Devis à prix fixe', en: 'Fixed-price quote', tr: 'Sabit fiyat teklifi', ku: 'Pêşniyara bihayê sabît' },
  'home.proc2.d': {
    de: 'Wenige Tage später ein schriftliches Angebot — mit Umfang, Preis und Termin.',
    fr: 'Quelques jours plus tard, un devis écrit — périmètre, prix et délai.',
    en: 'A few days later, a written quote — scope, price and timeline.',
    tr: 'Birkaç gün içinde yazılı teklif — kapsam, fiyat ve tarih.',
    ku: 'Çend roj şûnde pêşniyareke nivîskî — bi naverok, biha û demê.',
  },
  'home.proc3.t': { de: 'Umsetzung', fr: 'Réalisation', en: 'Build & setup', tr: 'Uygulama', ku: 'Pêkanîn' },
  'home.proc3.d': {
    de: 'Wir bauen und richten ein. Sie sehen Zwischenstände und entscheiden mit.',
    fr: 'Nous construisons et installons. Vous voyez les étapes et décidez avec nous.',
    en: 'We build and set up. You see progress along the way and have your say.',
    tr: 'Biz kurar ve ayarlarız. Siz ara aşamaları görür, karara katılırsınız.',
    ku: 'Em ava dikin û saz dikin. Hûn qonaxan dibînin û beşdarî biryarê dibin.',
  },
  'home.proc4.t': { de: 'Übergabe & Betreuung', fr: 'Remise & suivi', en: 'Handover & support', tr: 'Teslim ve destek', ku: 'Radestkirin û piştgirî' },
  'home.proc4.d': {
    de: 'Einweisung für Ihr Team — danach bleiben wir Ihr Ansprechpartner.',
    fr: 'Prise en main pour votre équipe — puis nous restons votre interlocuteur.',
    en: 'A walkthrough for your team — and we stay your point of contact.',
    tr: 'Ekibinize kullanım eğitimi — sonrasında muhatabınız olmaya devam ederiz.',
    ku: 'Perwerde ji bo tîma we — paşê em kesê we yê têkiliyê dimînin.',
  },
  'home.ref.label': { de: 'Referenzen', fr: 'Références', en: 'References', tr: 'Referanslar', ku: 'Referans' },
  'home.ref.title': {
    de: 'Betriebe aus der Region,<br /><em>die schon digital sind</em>.',
    fr: 'Des entreprises de la région<br /><em>déjà passées au numérique</em>.',
    en: 'Local businesses<br /><em>that already made the move</em>.',
    tr: 'Dijitale geçmiş<br /><em>bölge işletmeleri</em>.',
    ku: 'Karsaziyên herêmê<br /><em>ku jixwe dîjîtal in</em>.',
  },
  'home.ref.all': { de: 'Alle Referenzen', fr: 'Toutes les références', en: 'All references', tr: 'Tüm referanslar', ku: 'Hemû referans' },
  'home.region.label': { de: 'Region', fr: 'Région', en: 'Area', tr: 'Bölge', ku: 'Herêm' },
  'home.region.title': {
    de: 'Zuhause in Freiburg.<br /><em>Unterwegs in ganz Baden-Württemberg.</em>',
    fr: 'Basés à Fribourg.<br /><em>Présents dans tout le Bade-Wurtemberg.</em>',
    en: 'Based in Freiburg.<br /><em>Working across Baden-Württemberg.</em>',
    tr: 'Merkezimiz Freiburg.<br /><em>Tüm Baden-Württemberg’deyiz.</em>',
    ku: 'Navenda me Freiburg e.<br /><em>Li seranserê Baden-Württemberg.</em>',
  },
  'home.region.text': {
    de: 'Im Breisgau, in der Ortenau, im Markgräflerland und im Schwarzwald kommen wir persönlich vorbei. Betriebe im übrigen Baden-Württemberg betreuen wir per Video — und fahren zum Termin, wenn es nötig ist.',
    fr: 'Dans le Brisgau, l’Ortenau, le Markgräflerland et la Forêt-Noire, nous venons en personne. Ailleurs dans le Bade-Wurtemberg, nous travaillons en visio — et nous nous déplaçons si nécessaire.',
    en: 'In the Breisgau, Ortenau, Markgräflerland and the Black Forest we come by in person. Businesses elsewhere in Baden-Württemberg we support by video — and travel for appointments when needed.',
    tr: 'Breisgau, Ortenau, Markgräflerland ve Kara Orman’da yüz yüze geliyoruz. Baden-Württemberg’in geri kalanındaki işletmelerle görüntülü çalışıyor, gerektiğinde yerinde buluşuyoruz.',
    ku: 'Li Breisgau, Ortenau, Markgräflerland û Daristana Reş em bi xwe tên. Karsaziyên li deverên din ên Baden-Württemberg em bi vîdyoyê dişopînin — û gava pêwîst be em tên cem wan.',
  },
  'home.region.onsite': { de: 'Persönlich vor Ort', fr: 'Sur place', en: 'On site', tr: 'Yerinde', ku: 'Li cih' },
  'home.region.remote': { de: 'Per Video & nach Absprache', fr: 'En visio & sur rendez-vous', en: 'By video & by arrangement', tr: 'Görüntülü ve randevuyla', ku: 'Bi vîdyoyê û bi lihevkirinê' },
  'home.team.label': { de: 'Ihr Ansprechpartner', fr: 'Votre interlocuteur', en: 'Your contact', tr: 'Muhatabınız', ku: 'Kesê we yê têkiliyê' },
  'home.team.title': {
    de: 'Ein Gesicht statt<br /><em>einer Hotline</em>.',
    fr: 'Un visage plutôt<br /><em>qu’une hotline</em>.',
    en: 'A face instead of<br /><em>a hotline</em>.',
    tr: 'Çağrı merkezi değil,<br /><em>tanıdık bir yüz</em>.',
    ku: 'Rûyek li şûna<br /><em>xeta telefonê</em>.',
  },
  'home.team.text': {
    de: 'Hinter Breisgau Digital steht Hamza Öztürk, Fachinformatiker (IHK) und Gründer. Er hat Websites, Buchungssysteme und Warenwirtschaft für Betriebe in Südbaden gebaut — und ist für Sie direkt erreichbar, auf Deutsch, Englisch oder Türkisch.',
    fr: 'Derrière Breisgau Digital : Hamza Öztürk, informaticien diplômé (IHK) et fondateur. Il a conçu des sites, des systèmes de réservation et de gestion pour des entreprises du sud du Bade — et vous le joignez directement, en allemand, anglais ou turc.',
    en: 'Behind Breisgau Digital is Hamza Öztürk, IHK-certified IT specialist and founder. He has built websites, booking systems and inventory software for businesses in southern Baden — and you reach him directly, in German, English or Turkish.',
    tr: 'Breisgau Digital’in arkasında kurucu ve IHK sertifikalı bilişim uzmanı Hamza Öztürk var. Güney Baden’deki işletmeler için web siteleri, rezervasyon ve stok sistemleri geliştirdi — kendisine Almanca, İngilizce veya Türkçe doğrudan ulaşabilirsiniz.',
    ku: 'Li pişt Breisgau Digital Hamza Öztürk heye, pisporê IT (IHK) û damezrîner. Wî ji bo karsaziyên li başûrê Badenê malper, sîstemên rezervasyonê û rêveberiya depoyê ava kirine — û hûn dikarin rasterast bi Almanî, Îngilîzî an Tirkî pê re biaxivin.',
  },
  'home.team.role': {
    de: 'Gründer · Fachinformatiker (IHK)', fr: 'Fondateur · informaticien (IHK)', en: 'Founder · IT specialist (IHK)', tr: 'Kurucu · Bilişim uzmanı (IHK)', ku: 'Damezrîner · Pisporê IT (IHK)',
  },
  'home.faq.label': { de: 'Häufige Fragen', fr: 'Questions fréquentes', en: 'FAQ', tr: 'Sık sorulanlar', ku: 'Pirsên pir tên pirsîn' },
  'home.faq.title': {
    de: 'Was Betriebe<br /><em>uns zuerst fragen</em>.',
    fr: 'Ce que les entreprises<br /><em>nous demandent d’abord</em>.',
    en: 'What businesses<br /><em>ask us first</em>.',
    tr: 'İşletmelerin<br /><em>ilk sorduğu sorular</em>.',
    ku: 'Karsazî<br /><em>pêşî çi ji me dipirsin</em>.',
  },
  'home.faq1.q': { de: 'Was kostet eine Website?', fr: 'Combien coûte un site web ?', en: 'How much does a website cost?', tr: 'Bir web sitesi ne kadar?', ku: 'Malperek çiqas e?' },
  'home.faq1.a': {
    de: 'Eine kompakte Firmen-Website beginnt bei {p} € zum Festpreis. Shop, Online-Buchung oder mehrere Sprachen kalkulieren wir nach dem kostenlosen Erstgespräch — schriftlich und bevor wir anfangen.',
    fr: 'Un site vitrine compact commence à {p} €, à prix fixe. Boutique, réservation en ligne ou plusieurs langues sont chiffrées après le premier échange gratuit — par écrit et avant de commencer.',
    en: 'A compact business website starts at €{p}, at a fixed price. Shops, online booking or multiple languages are quoted after the free first consultation — in writing, before we start.',
    tr: 'Kompakt bir kurumsal web sitesi sabit fiyatla {p} €’dan başlar. Mağaza, online rezervasyon veya birden fazla dil, ücretsiz ön görüşmeden sonra yazılı olarak ve başlamadan önce fiyatlandırılır.',
    ku: 'Malpereke karsaziyê ya kompakt bi bihayê sabît ji {p} € dest pê dike. Firotgeh, rezervasyona serhêl an çend ziman piştî hevdîtina yekem a belaş têne hesabkirin — bi nivîskî û berî ku em dest pê bikin.',
  },
  'home.faq2.q': { de: 'Muss ich monatlich etwas zahlen?', fr: 'Faut-il payer chaque mois ?', en: 'Do I have to pay monthly?', tr: 'Aylık ödeme yapmam gerekiyor mu?', ku: 'Ma divê ez her meh tiştekî bidim?' },
  'home.faq2.a': {
    de: 'Bewertungskarten und die Smart-Home-Einrichtung zahlen Sie einmalig. Bei einer Website kommen nur Domain und Hosting dazu, meist wenige Euro im Monat. Pflege und Änderungen gibt es auf Wunsch als Paket — Pflicht ist das nicht.',
    fr: 'Les cartes d’avis et l’installation domotique se paient une seule fois. Pour un site, seuls le domaine et l’hébergement s’ajoutent, généralement quelques euros par mois. Maintenance et modifications en option — rien d’obligatoire.',
    en: 'Review cards and the smart-home setup are one-off payments. A website only adds domain and hosting, usually a few euros a month. Maintenance and changes are available as an optional package — nothing mandatory.',
    tr: 'Değerlendirme kartları ve akıllı ev kurulumu tek seferlik ödenir. Web sitesinde yalnızca alan adı ve barındırma eklenir, genellikle ayda birkaç euro. Bakım ve değişiklikler isteğe bağlı paket olarak sunulur — zorunlu değildir.',
    ku: 'Kartên nirxandinê û sazkirina mala biaqil yek car têne dayîn. Ji bo malperê tenê domain û hosting lê zêde dibin, bi gelemperî çend euro di mehê de. Lênêrîn û guhertin wek pakêteke vebijarkî hene — ne mecbûrî ye.',
  },
  'home.faq3.q': { de: 'Wie schnell geht das?', fr: 'Combien de temps faut-il ?', en: 'How long does it take?', tr: 'Ne kadar sürer?', ku: 'Çiqas dem dikişîne?' },
  'home.faq3.a': {
    de: 'Bewertungskarten sind in der Regel 5–7 Werktage nach Freigabe bei Ihnen. Eine Firmen-Website steht meist nach 2–4 Wochen, eine Smart-Home-Einrichtung vor Ort dauert oft nur einen Tag.',
    fr: 'Les cartes d’avis arrivent généralement 5 à 7 jours ouvrés après validation. Un site vitrine est prêt en 2 à 4 semaines, et une installation domotique sur place prend souvent une seule journée.',
    en: 'Review cards usually arrive 5–7 working days after approval. A business website is typically ready in 2–4 weeks, and an on-site smart-home setup often takes a single day.',
    tr: 'Değerlendirme kartları onaydan sonra genellikle 5–7 iş günü içinde elinizde olur. Kurumsal bir web sitesi çoğunlukla 2–4 haftada hazırdır; yerinde akıllı ev kurulumu çoğu zaman tek gün sürer.',
    ku: 'Kartên nirxandinê bi gelemperî 5–7 rojên xebatê piştî pejirandinê digihîjin we. Malpereke karsaziyê bi gelemperî di 2–4 hefteyan de amade ye, û sazkirina mala biaqil li cih pir caran tenê rojekê dikişîne.',
  },
  'home.faq4.q': { de: 'Kommen Sie auch außerhalb von Freiburg?', fr: 'Venez-vous aussi en dehors de Fribourg ?', en: 'Do you work outside Freiburg?', tr: 'Freiburg dışına da geliyor musunuz?', ku: 'Hûn derveyî Freiburgê jî tên?' },
  'home.faq4.a': {
    de: 'Ja. Im Breisgau, in der Ortenau, im Markgräflerland und im Schwarzwald persönlich; im übrigen Baden-Württemberg per Video und bei Bedarf vor Ort. Bewertungskarten verschicken wir deutschlandweit.',
    fr: 'Oui. En personne dans le Brisgau, l’Ortenau, le Markgräflerland et la Forêt-Noire ; ailleurs dans le Bade-Wurtemberg en visio et sur place si besoin. Les cartes d’avis sont expédiées dans toute l’Allemagne.',
    en: 'Yes. In person across the Breisgau, Ortenau, Markgräflerland and Black Forest; elsewhere in Baden-Württemberg by video and on site when needed. Review cards ship anywhere in Germany.',
    tr: 'Evet. Breisgau, Ortenau, Markgräflerland ve Kara Orman’da yüz yüze; Baden-Württemberg’in geri kalanında görüntülü ve gerektiğinde yerinde. Değerlendirme kartlarını tüm Almanya’ya gönderiyoruz.',
    ku: 'Erê. Li Breisgau, Ortenau, Markgräflerland û Daristana Reş bi xwe; li deverên din ên Baden-Württemberg bi vîdyoyê û gava pêwîst be li cih. Kartên nirxandinê em li seranserê Almanyayê dişînin.',
  },
  'home.faq5.q': {
    de: 'Ich bin nicht technisch — ist das ein Problem?', fr: 'Je ne suis pas technicien — est-ce un problème ?', en: 'I’m not technical — is that a problem?', tr: 'Teknolojiden anlamıyorum — sorun olur mu?', ku: 'Ez ne teknîkî me — ma ev pirsgirêk e?',
  },
  'home.faq5.a': {
    de: 'Nein, genau dafür gibt es uns. Wir erklären alles ohne Fachbegriffe, richten alles fertig ein und zeigen Ihrem Team, wie es geht. Wenn später etwas ist, rufen Sie einfach an.',
    fr: 'Non, c’est justement notre rôle. Nous expliquons tout sans jargon, installons tout et montrons à votre équipe comment faire. En cas de souci, un simple appel suffit.',
    en: 'No — that’s exactly what we’re here for. We explain everything without jargon, set it all up and show your team how it works. If anything comes up later, just call.',
    tr: 'Hayır, biz tam da bunun için varız. Her şeyi teknik terim kullanmadan anlatır, hazır kurar ve ekibinize nasıl kullanılacağını gösteririz. Sonradan bir şey olursa aramanız yeterli.',
    ku: 'Na, em ji bo vê yekê hene. Em her tiştî bê peyvên teknîkî rave dikin, amade saz dikin û nîşanî tîma we didin. Heke paşê tiştek hebe, tenê telefon bikin.',
  },
  'home.cta.or': { de: 'oder direkt', fr: 'ou directement', en: 'or directly', tr: 'ya da doğrudan', ku: 'an rasterast' },
};
